### ISSUE TITLE
Mint flow feedback and polishing

### ISSUE THREAD

**Issue by jsonsivar** [fleekxyz/non-fungible-apps#125]
@csosamorales Putting down an initial list and we can move things into Shortcut and prioritize as needed. But thought we'd start with a list here and include @rollsmorr1 in the discussion.

1. Does it feel kinda weird that the substeps in the github flow don't change the step 1? How in sync should the step number and the modals be?
2. What is the first search textbox for in the Select Repository step?
3. Show the org name in the Select Repository and Configure Repository step?
4. On the Configure Repository step, we default to a commit but not the branch so we should also default the branch we are taking the default commit from right?
5. Tool tips for the steps
6. From @rollsmorr1: move the verificaiton checkmark to it's own step.

**Comment by jsonsivar** [comment]
More
* Make the 2 search boxes clearer on what to do
* Make branch selection typeable

**Comment by jsonsivar** [comment]
Non UI related:
No approvals
First version should be on mainnet
Twitter handle instead of ENS

**Comment by EmperorOrokuSaki** [comment]
Tagging to confirm if this issue is dead @jsonsivar @csosamorales

**Comment by jsonsivar** [comment]
Good catch I think it is.  But will let @csosamorales confirm
