### ISSUE TITLE
Expose last token id function in the contract

### ISSUE THREAD

**Issue by zoruka** [fleekxyz/non-fungible-apps#45]
We need to have a view function in the contract to retrieve the last token id.
If we have the last token id the client side can fetch last tokens backwards from last token id to 0.

**Comment by rajpatil7322** [comment]
Hey can you give some description for this problem .....I'll help.

**Comment by jsonsivar** [comment]
Thanks for your interest @rajpatil7322 .  Will tag @zoruka here to confirm if we still need this.

**Comment by EmperorOrokuSaki** [comment]
Hi @rajpatil7322! Thanks for your interest and sorry for the late response!

This issue refers to exposing a function on the FleekERC721 contract that returns the last token index (the total count of tokens in other words). This function will be used on the Fleek NFA front-end to fetch the latest additions to the collection.

I suggest you and all contributors read [the contribution guideline](https://github.com/fleekxyz/non-fungible-apps/blob/fix/contributing/CONTRIBUTING.md) for further information about how we process contributions for the Fleek NFA project.

Feel free to tag me if you have any questions 🙂
