### ISSUE TITLE
Verify what is wrong with minted token

### ISSUE THREAD

**Issue by zoruka** [fleekxyz/non-fungible-apps#46]
Token 4 metadata is broken [https://testnets.opensea.io/assets/mumbai/0xb8594dc01580884ad69fe5d78edea5e66beb5ffa/4](https://testnets.opensea.io/assets/mumbai/0xb8594dc01580884ad69fe5d78edea5e66beb5ffa/4)

**Comment by csosamorales** [comment]
Researching on OpenSea found an [example](https://opensea.io/assets/ethereum/0xd2ff891f5556c623f36a3f22b0e4815a3e36dc23/22) that has a break line. Inspecting the code, it separates with <p> tag.

Looks like zoruka already tried to add a description with [break lines](https://testnets.opensea.io/assets/mumbai/0xb8594dc01580884ad69fe5d78edea5e66beb5ffa/7)

**Comment by csosamorales** [comment]
Possible approach but I don't like too much to use dangerouslySetInnerHTML

```
 <AccordionItem
      heading="Description"
      minH={120}
      maxH="auto"
      children={
         <div
           dangerouslySetInnerHTML={{
              __html:
                 '<p>' +
                 description.replaceAll('\n', '</p><p>') +
                '</p>',
          }}
         />
      }
 />
```

Also, in OpenSea it wouldn't be shown correctly anyway
