### ISSUE TITLE
Does returning array cost a lot more than returning individual records?

### ISSUE THREAD

**Issue by jsonsivar** [fleekxyz/non-fungible-apps#51]
If so maybe for stuff like this we can return count and query by index instead of  returning all at the same time? https://github.com/fleekxyz/contracts/pull/28/files#diff-bbeb76371c7a5bba209b302f386ffbcd6c237e832ec79d27542786fa76eb1335R88

**Comment by EmperorOrokuSaki** [comment]
Discussed in Discord.
