### ISSUE TITLE
Add view function to enable other contracts to interact with token metadata

### ISSUE THREAD

**Issue by zoruka** [fleekxyz/non-fungible-apps#93]
> This issue was originally brought by @daltoncoder

There is a view function tokenURI to get all an NFA's metadata. But only in JSON form. Making it a bit trickier for contracts or a program that is not a frontend to get and use this data. Since view functions are free, might be a good idea to expose a function that just returns the app struct in non string form.

**Comment by EmperorOrokuSaki** [comment]
PR: #119
